/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Feb 14 2023
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

#define _XTAL_FREQ 4M
#define RS RC0
#define EN RC1
#define RW RC2
#define delay for(j=0;j<100;j++)

#pragma config FOSC = XT 
#pragma config WDTE = OFF 
#pragma config PWRTE = ON 
#pragma config BOREN = ON 
#pragma config LVP = OFF 
#pragma config CPD = OFF 
#pragma config WRT = OFF 
#pragma config CP = OFF

int j;

void instCtrl(unsigned char data)
{
    PORTB= data;
    RS=0;
    RW=0;
    EN=1;
    delay;
    EN=0;
}

void initLCD()
{
    instCtrl(0x38); // 0011 1000 -> 8 bits for data + 2 line display + 5 by 7 dot matris + X +X where X is dont care bits
    instCtrl(0x08); //turning off
    instCtrl(0x01); //clearing display
    instCtrl(0x06); // entry mode set 
    instCtrl(0x0C); // 0000 1100  -> turning display on | L L L L H D C B | Where D is high when display on nad L when off | C is for curose 1 = on 0 = off | B is for blinkin 1 = on 0 = off
    instCtrl(0x06); // 0000 0110 -> 
    instCtrl(0x80); // 1000 0000 
   
   
}

void dataCtrl(unsigned char b)
{
    PORTB=b;
    RS=1;
    RW=0;
    EN=1;
    delay;
    EN=0;
}
void show(const unsigned char *s)
{
    while(*s) {
        dataCtrl(*s++);
    }
}
void main(void)
 {
    
    TRISB = 0X00;
    TRISC = 0X00;
    TRISD = 0XFF;
    
    // Intializing LCD
    initLCD();
    instCtrl(0x80); //forcing the cursor at 0x80 position
     instCtrl(0x01);
    int read= 0x00;
    int count = 0x00;

   // Write your code here
   while (1)
   {
      
      if(RD4 == 1)
      {
	 
	  read = PORTD & 0x0F;
	 if(count==20 )
		 instCtrl(0xC0);
	 else if(count==40)
	         instCtrl(0x94);
	 else if(count==60)
	    instCtrl(0xD4);
	  else if(count==80)
	  {
	     	instCtrl(0x01);
	       count=0;
	  }
	  
	 switch(read)
	 {
	     case 0x00:
		  show("1"); count++; while(RD4 ==1);
		  break;
	       case 0x01:
		  show("2"); count++; while(RD4 ==1);
		  break;
	       case 0x02:
		  show("3"); count++; while(RD4 ==1);
		  break;
	       case 0x04:
		  show("4"); count++; while(RD4 ==1);
		  break;
	        case 0x05:
		  show("5"); count++; while(RD4 ==1);
		  break;
		 case 0x06:
		  show("6"); count++; while(RD4 ==1);
		  break;
		  case 0x08:
		  show("7"); count++; while(RD4 ==1);
		  break;
		  case 0x09:
		  show("8"); count++; while(RD4 ==1);
		  break;
		  case 0x0A:
		  show("9"); count++; while(RD4 ==1);
		  break;
		  case 0x0C:
		  show("*"); count++; while(RD4 ==1);
		  break;
		  case 0x0D:
		  show("0"); count++; while(RD4 ==1);
		  break;
		  case 0x0E:
		  show("#"); count++;while(RD4 ==1);
		  break;
	 }
      }
      
     
      
      
   }
   
      ;
 }

 