/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Feb 21 2023
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include <pic.h>
#include <stdlib.h>


#pragma config FOSC = XT 
#pragma config WDTE = OFF 
#pragma config PWRTE = ON 
#pragma config BOREN = ON 
#pragma config LVP = OFF 
#pragma config CPD = OFF 
#pragma config WRT = OFF 
#pragma config CP = OFF

#define _XTAL_FREQ 4M


void interrupt ISR() 
 { 
   GIE = 0; // disables all unmasked interrupts to prevent interrupt overlap 
    if (INTF) // check the interrupt flag 
    { 
    
    /* write the interrupt service routine here for RB0/INT external interrupt */ 
       int read;  
       read = PORTD & 0x0F;
	  
	 switch(read)
	 {
	     case 0x00:
		 PORTC=0x01;
		  break;
	       case 0x01:
		  PORTC=0x02;
		  break;
	       case 0x02:
		  PORTC=0x03;
		  break;
	       case 0x04:
		  PORTC=0x04;
		  break;
	        case 0x05:
		   PORTC=0x05;
		  break;
		 case 0x06:
		    PORTC=0x06;
		  break;
		  case 0x08:
		     PORTC=0x07;
		  break;
		  case 0x09:
		     PORTC=0x08;
		  break;
		  case 0x0A:
		     PORTC=0x09;
		  break;
		  case 0x0C:
		     PORTC=0x00;
		  break;
		  case 0x0D:
		     PORTC=0x00;
		  break;
		  case 0x0E:
		     PORTC=0x00;
		  break;
	 }
	
	 INTF = 0; // clears the interrupt flag 
       
       
    } 
   
   GIE = 1; // enable interrupts again 
 }


 
void main(void)
 {
    GIE  = 1; //Enabling Global Interrupt
    INTE = 1; //Enabling RB0/INT interrupt
    INTF = 0; //Setting RB0/INT interrupt flag to 0
    OPTION_REG = 0x43; // PS2:PS0 - prescaler 1:16 
			              // PSA - prescaler assignment to TMR0 
                                      // T0CS - internal instruction cycle clock 
                                       // T0SE - not used since clock is internal 
    TRISB = 0x01;
    TRISC = 0x00;
    TRISD= 0xFF;
    PORTC = 0x05;

   // Write your code here
   while (1)
   {
   }  
   
 }